export const config = {
  streamUrl: import.meta.env.VITE_STREAM_URL || "",
  calendarUrl: import.meta.env.VITE_CALENDAR_URL || "",
  eventsUrl: import.meta.env.VITE_EVENTS_URL || "",
  indexUrl: import.meta.env.VITE_INDEX_URL || "",
  wsUrl: import.meta.env.VITE_WS_URL || "",
  historyUrl: import.meta.env.VITE_HISTORY_URL || "",
  corsUrl: import.meta.env.VITE_CORS_URL || "${url}",
  userIdle: 10000,
  messageDelay: 20,
  perfStart: "2021-04-01T18:00:00.002Z",
  facebookUrl: import.meta.env.VITE_FACEBOOK_URL || "",
  instagramUrl: import.meta.env.VITE_INSTAGRAM_URL || "",
  twitterUrl: import.meta.env.VITE_TWITTER_URL || "",
  youtubeUrl: import.meta.env.VITE_YOUTUBE_URL || "",
  showButtons: import.meta.env.VITE_SHOW_BUTTONS || false,
};
