export const config = {
  streamUrl: import.meta.env.VITE_STREAM_URL || "",
  calendarUrl: import.meta.env.VITE_CALENDAR_URL || "",
  eventsUrl: import.meta.env.VITE_EVENTS_URL || "",
  indexUrl: import.meta.env.VITE_INDEX_URL || "",
  wsUrl: import.meta.env.VITE_WS_URL || "",
  historyUrl: import.meta.env.VITE_HISTORY_URL || "",
  corsUrl: import.meta.env.VITE_CORS_URL || "${url}",
  facebookUrl: import.meta.env.VITE_FACEBOOK_URL || "",
  instagramUrl: import.meta.env.VITE_INSTAGRAM_URL || "",
  twitterUrl: import.meta.env.VITE_TWITTER_URL || "",
  youtubeUrl: import.meta.env.VITE_YOUTUBE_URL || "",
  emailUrl: import.meta.env.VITE_EMAIL_URL || "",
  newFeatures: import.meta.env.VITE_NEW_FEATURES === "true" || false,
  fientaUrl: import.meta.env.VITE_FIENTA_URL || "",
  fientaToken: import.meta.env.VITE_FIENTA_TOKEN || "",
  fientaTestcode: import.meta.env.VITE_FIENTA_TESTCODE || "",
  userUpdateRate: 30 * 1000,
  userUpdatedSinceLimit: 30 * 1000,
  messageDelay: 50,
  perfStart: "2021-04-01T18:00:00.002Z",
};
